# Strategy Selection Filters Configuration
# Simple criteria for strategy selection

# Basic quality thresholds
quality_filters:
  min_total_score: 0.6
  min_probability_of_profit: 0.5
  min_conviction_levels:
    - MEDIUM
    - HIGH
    - VERY_HIGH

# Strategy selection by market cap
strategy_by_market_cap:
  large_cap:
    allowed_strategies: all  # Most liquid, all strategies allowed
    complexity_allowed: high
    min_liquidity_score: 0.3
    
  mid_cap:
    allowed_strategies:
      - Iron Condor
      - Bull Call Spread
      - Bear Put Spread
      - Butterfly Spread
      - Calendar Spread
      - Cash-Secured Put
      - Covered Call
    complexity_allowed: medium
    min_liquidity_score: 0.4
    
  small_cap:
    allowed_strategies:
      - Bull Call Spread
      - Bear Put Spread
      - Long Call
      - Long Put
      - Cash-Secured Put
    complexity_allowed: low
    min_liquidity_score: 0.5
    
  micro_cap:
    allowed_strategies:
      - Long Call
      - Long Put
      - Bull Call Spread
      - Bear Put Spread
    complexity_allowed: low
    min_liquidity_score: 0.6

# Strategy ranking priorities
ranking_priorities:
  - field: conviction_level
    order:
      - VERY_HIGH
      - HIGH
      - MEDIUM
      - LOW
  - field: total_score
    order: desc
  - field: probability_of_profit
    order: desc

# Risk filters by industry rating
risk_by_industry_rating:
  strong_overweight:
    min_probability: 0.35
    min_risk_reward: 2.0
    allow_directional: true
    
  moderate_overweight:
    min_probability: 0.45
    min_risk_reward: 1.5
    allow_directional: false
    
  strong_underweight:
    min_probability: 0.40
    min_risk_reward: 1.8
    allow_directional: true
    
  moderate_underweight:
    min_probability: 0.50
    min_risk_reward: 1.5
    allow_directional: false